id: I7A5BB3C3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-25T11:20:41+00:00'
last_modified: '2022-06-14T08:18:19.473696+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN10628
  title: རྫོགས་རིམ་རིམ་ལྔ་གསལ་སྒྲོན།
  author: ''
  base:
    97BE:
      image_group_id: I3CN10630
      title: ''
      total_pages: ''
      order: 1
      base_file: 97BE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
